import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
export const metadata: Metadata = {
  title: "suzuki fatehjang motors",
  description: "Generated by create Awais Aziz",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${GeistMono.variable} h-full antialiased `}
    >
      <body className="min-h-full flex ">
        {children}
      </body>
    </html>
  );
}