import { Inter } from "next/font/google";
import "@/scss/index.scss";
import type { Metadata, Viewport } from "next";

import Providers from "@/app/[locale]/providers";
import Header from "@/app/[locale]/common/header";
import NavLinks from "@/app/[locale]/common/nav-links";
import Footer from "@/app/[locale]/common/footer";
import TrackingManager from "./common/tracking-manager";
import TopBar from "./common/topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "App",
  description: "Generated by Next.js",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  colorScheme: "light",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} min-h-full flex flex-col`}>

        <Providers>
          <TrackingManager />

          {/* 🔥 TOP BAR (FIRST) */}
          {/* <TopBar /> */}

          {/* 🔥 HEADER (SECOND) */}
          <Header>
            <NavLinks />
          </Header>

          {/* MAIN CONTENT */}
          <main className="flex-1">{children}</main>

          {/* FOOTER */}
          <Footer />

        </Providers>

      </body>
    </html>
  );
}